name: beer_me_up
description: An app about beers

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.1

  http: 0.11.3+16

  shared_preferences: 0.4.1

  sealed_unions: 2.0.0
  flutter_stream_friends: 0.8.0

  intl: 0.15.6

  google_sign_in: 3.0.2
  flutter_facebook_login: 1.1.1
  firebase_auth: 0.5.5
  cloud_firestore: 0.6.3
  firebase_analytics: 0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/round_logo.png
    - images/thinking_face.png
    - images/large_logo.png
    - images/toolbar_icon.png
    - images/beer_icon_background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: beers
       fonts:
         - asset: fonts/beers.ttf
     - family: Google Sans
       fonts:
         - asset: fonts/GoogleSans-Regular.ttf
         - asset: fonts/GoogleSans-Medium.ttf
           weight: 500
         - asset: fonts/GoogleSans-Bold.ttf
           weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
